-- Set up only known period - 2012-2013
INSERT INTO INCOME_RATE_PERIOD (ID, START_DATE, END_DATE) VALUES (1, '2012-07-01', '2013-06-30')

-- Set up income period tax brackets
INSERT INTO INCOME_RATE_TAX_BRACKET (ID, INCOME_RATE_PERIOD_ID, BRACKET_START_VALUE, BRACKET_END_VALUE, TAX_RATE_PERCENTAGE, ADDITIONAL_TAX_AMOUNT) VALUES (1, 1, 0, 18200, 0, 0) 

INSERT INTO INCOME_RATE_TAX_BRACKET (ID, INCOME_RATE_PERIOD_ID, BRACKET_START_VALUE, BRACKET_END_VALUE, TAX_RATE_PERCENTAGE, ADDITIONAL_TAX_AMOUNT) VALUES (2, 1, 18201, 37000, 0.19, 0)

INSERT INTO INCOME_RATE_TAX_BRACKET (ID, INCOME_RATE_PERIOD_ID, BRACKET_START_VALUE, BRACKET_END_VALUE, TAX_RATE_PERCENTAGE, ADDITIONAL_TAX_AMOUNT) VALUES (3, 1, 37001, 80000, 0.325, 3572)

INSERT INTO INCOME_RATE_TAX_BRACKET (ID, INCOME_RATE_PERIOD_ID, BRACKET_START_VALUE, BRACKET_END_VALUE, TAX_RATE_PERCENTAGE, ADDITIONAL_TAX_AMOUNT) VALUES (4, 1, 80001, 180000, 0.37, 17547)

INSERT INTO INCOME_RATE_TAX_BRACKET (ID, INCOME_RATE_PERIOD_ID, BRACKET_START_VALUE, BRACKET_END_VALUE, TAX_RATE_PERCENTAGE, ADDITIONAL_TAX_AMOUNT) VALUES (5, 1, 180001, null, 0.45, 54547)